const numericRepresentationOfTheDayOfTheWeek = 5

if (numericRepresentationOfTheDayOfTheWeek === 1)
    console.log(`${numericRepresentationOfTheDayOfTheWeek} - Это Понедельник`)
else if (numericRepresentationOfTheDayOfTheWeek === 2)
    console.log(`${numericRepresentationOfTheDayOfTheWeek} - Это Вторник`)
else if (numericRepresentationOfTheDayOfTheWeek === 3)
    console.log(`${ numericRepresentationOfTheDayOfTheWeek } - Это Среда`)
else if (numericRepresentationOfTheDayOfTheWeek === 4)
    console.log(`${ numericRepresentationOfTheDayOfTheWeek } - Это Четверг`)
else if (numericRepresentationOfTheDayOfTheWeek === 5)
    console.log(`${ numericRepresentationOfTheDayOfTheWeek } - Это Пятница`)
else if (numericRepresentationOfTheDayOfTheWeek === 6)
    console.log(`${ numericRepresentationOfTheDayOfTheWeek } - Это Суббота`)
else if (numericRepresentationOfTheDayOfTheWeek === 7)
    console.log(`${ numericRepresentationOfTheDayOfTheWeek } - Это Воскресенье`)
else console.log('Неверные данные')